spring:
  application:
    name: ChadGPT
  main:
    banner-mode: off
    web-application-type: none

# Disable logging to console and route to file.
logging:
  pattern:
    console:
  file:
    name: chad-gpt.log

chat-gpt:
  base-url: https://api.openai.com/v1/chat/completions
  api-key: ${CHAT_GPT_API_KEY}
  model: gpt-3.5-turbo
  max-tokens: